# conf/models/models.yaml

models:  
  SVC:
    _target_: sklearn.svm.SVC
    kernel: "rbf"
    C: 1.0
    probability: True

  RForest:
    _target_: sklearn.ensemble.RandomForestClassifier
    n_estimators: 200

  KNN:        
    _target_: sklearn.neighbors.KNeighborsClassifier
    n_neighbors: 5

  MLP:
    _target_: sklearn.neural_network.MLPClassifier
    hidden_layer_sizes: [128, 64]
    max_iter: 1000